apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-api
  labels:
    app: wishlist-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wishlist-api
  template:
    metadata:
      labels:
        app: wishlist-api
    spec:
      containers:
      - name: wishlist-api
        image: wishlist-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: wishlist-secrets
              key: database-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: wishlist-secrets
              key: secret-key
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20 